#!/bin/bash

# This script will be located @ /data/home/copy_dir/tmp
# cmc-home is a clean home dir list from engrcmc-home
# cmc-home will be located @ /data/home/copy_dir/tmp
# homedirchecknormallog is the normal log for home dir check
# homedircheckerrorlog is the error log for home dir check

today=`date '+%Y_%m_%d_%H_%M_%S'`;
logfile="/data/home/copy_dir/tmp/homedirchecknormallog_$today"
/bin/touch $logfile
errorlogfile="/data/home/copy_dir/tmp/homedircheckerrorlog_$today"
/bin/touch $errorlogfile

function chk {
  if [ $? -ne 0 ] ; then
    /bin/echo "ERROR: $1"
    exit 1
  fi
}

function cmc-subdir {
if [ -d "/data/home/$1" ]
then
   if [ ! -d "/data/home/$1/cmc" ]
      then
      /bin/mkdir -p /data/home/$1/cmc
      chk "cannot create subdir for $1" >> $errorlogfile
      /bin/echo "make cmc subdir for $1" >> $logfile
   fi
else
   /bin/echo "/data/home/$1 doesn't exist" >> $errorlogfile
fi
}

while IFS= read -r THELINE; do
  if [ -n "$THELINE" ]; then
     if [ "$THELINE" == "llixiang" ]
     then
        # nsid for llixiang is lil997 
        cmc-subdir lil997
     else
        # normal nsid
        cmc-subdir $THELINE
     fi
  fi
done < /data/home/copy_dir/tmp/cmc-home
