#!/bin/bash

# This script will be located @ /data/home/copy_dir/tmp
# cmc-home is a clean home dir list from engrcmc-home
# cmc-home will be located @ /data/home/copy_dir/tmp
# movedatalog is the normal action log
# movedataerrorlog is the error log 

today=`/bin/date '+%Y_%m_%d_%H_%M_%S'`;
logfile="/data/home/copy_dir/tmp/movedatalog_$today"
/bin/touch $logfile
errorlogfile="/data/home/copy_dir/tmp/movedataerrorlog_$today"
/bin/touch $errorlogfile

function chk {
  if [ $? -ne 0 ] ; then
    /bin/echo "ERROR: $1"
    exit 1
  fi
}

function move-to-cmc-subdir {
if [ -d "/data/home/$1/cmc" ]
then
   if [ $1 == lil997 ]
   then
      /bin/mv -f /data/home/copy_dir/llixiang/* /data/home/lil997/cmc/
      chk "can not move data for llixiang" >> $errorlogfile
      /bin/rm -r /data/home/copy_dir/llixiang
      chk "can not remove directory for llixiang" >> $errorlogfile
   else
      /bin/mv -f /data/home/copy_dir/$1/* /data/home/$1/cmc/
      chk "can not move data for $1" >> $errorlogfile
      /bin/rm -r /data/home/copy_dir/$1/
      chk "can not remove directory for $1" >> $errorlogfile
   fi
   /bin/chown -Rh $1:posixusers /data/home/$1/cmc
   chk "can not chown for $1" >> $errorlogfile
   /bin/echo "move data and change owner for $1" >> $logfile
else
   /bin/echo "/data/home/$1/cmc doesn't exist" >> $errorlogfile
fi
}

# fix permission
/bin/find /data/home/copy_dir -type d -print0 | /bin/xargs -0 chmod 700 
chk "can not fix permission for dir" >> $errorlogfile
/bin/find /data/home/copy_dir -type f -print0 | /bin/xargs -0 chmod go-rwx
chk "can not fix permission for file" >> $errorlogfile

while IFS= read -r THELINE; do
  if [ -n "$THELINE" ]; then
     if [ "$THELINE" == "llixiang" ]
     then
        # nsid for llixiang is lil997 
        move-to-cmc-subdir lil997
     else
        # normal nsid
        move-to-cmc-subdir $THELINE
     fi
  fi
done < /data/home/copy_dir/tmp/cmc-home
